# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- refs/tags/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: personalAccessToken
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run test
  displayName: 'npm install and test'

- script: |
    npm install -g vsce
    vsce publish -p $PERSONALACCESSTOKEN
  displayName: 'publish to marketplace'